---
name: Tests

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      CGO_ENABLED: 1

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.26"

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.5"
          extensions: mbstring, iconv, ctype, xml, dom, fileinfo, tokenizer, filter
          tools: none
        env:
          phpts: ts

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libsodium-dev libargon2-dev libonig-dev libxml2-dev
          sudo apt-get install --reinstall -y libbrotli-dev

      - name: Install Go tools
        run: |
          go install github.com/caddyserver/xcaddy/cmd/xcaddy@v0.4.4
          go install golang.org/x/vuln/cmd/govulncheck@v1.1.4

      - name: Configure CGO flags
        run: |
          echo "CGO_CFLAGS=-D_GNU_SOURCE $(php-config --includes)" >> $GITHUB_ENV
          echo "CGO_LDFLAGS=$(php-config --ldflags) $(php-config --libs)" >> $GITHUB_ENV

      - name: Build test FrankenPHP binary
        env:
          XCADDY_GO_BUILD_FLAGS: "-ldflags='-w -s' -tags=nobadger,nomysql,nopgx,nowatcher"
        run: |
          xcaddy build \
            --output frankenphp-test \
            --with github.com/dunglas/frankenphp@v1.12.3 \
            --with github.com/dunglas/frankenphp/caddy@v1.12.3 \
            --with github.com/dunglas/caddy-cbrotli@v1.0.1 \
            --with github.com/y-l-g/websocket/module=./module

      - name: Run Go tests
        env:
          GOFLAGS: "-tags=nobadger,nomysql,nopgx,nowatcher"
        run: |
          cp frankenphp-test ./module/frankenphp
          cd module
          go test -v -race .
          go test -v -race ./tests/integration/...
          govulncheck ./...

      - name: Install PHP dependencies
        run: composer install --prefer-dist --no-progress

      - name: Validate PHP package
        run: |
          composer validate --strict
          composer audit --locked

      - name: Run PHP tests
        run: ./frankenphp-test php-cli ./vendor/bin/phpunit -c lib/phpunit.xml lib

      - name: Run PHPStan
        run: ./vendor/bin/phpstan analyze --configuration=lib/phpstan.neon --error-format=github

  docker:
    name: Docker Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Build Docker image
        run: docker build .
